name: Node.js CI

on:
  push:
    branches:
      - main  # Chạy workflow khi có thay đổi ở nhánh main
  pull_request:
    branches:
      - main  # Chạy workflow khi có pull request vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
      # Bước 1: Kiểm tra mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Chọn phiên bản Node.js bạn muốn sử dụng

      # Bước 3: Cài đặt các dependencies từ package.json
      - name: Install dependencies
        run: npm install

      # Bước 4: Chạy unit tests với Jest
      - name: Run tests
        run: npm test

      # Bước 5: Triển khai (nếu cần, bạn có thể thay đổi bước này theo nhu cầu triển khai của bạn)
      - name: Deploy to server
        run: |
          echo "Deploying the Node.js application..."
          # Ví dụ deploy qua SSH (cần cấu hình key SSH trong GitHub Secrets)
          # ssh user@host "cd /path/to/app && git pull && npm install && pm2 restart app"
